import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const cfg=window.REFLECT_CONFIG||{},ready=cfg.SUPABASE_URL&&cfg.SUPABASE_ANON_KEY;
const $=s=>document.querySelector(s),auth=$('#auth'),journal=$('#journal'),localDay=()=>{const d=new Date(),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`},format=d=>new Date(`${d}T12:00:00`).toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});
let client,day=localDay(),record={daily_goal:'',gratitudes:[]},user;
const show=m=>$('#status').textContent=m,fit=()=>{const x=$('#goal');x.style.height='auto';x.style.height=Math.min(x.scrollHeight,210)+'px'},cacheKey=()=>`reflect-cache-${user?.id||'guest'}-${day}`;
function cache(){localStorage.setItem(cacheKey(),JSON.stringify(record))}function empty(){const e=$('#empty');e.hidden=record.gratitudes.length>0}function render(){ $('#date').textContent=format(day);$('#goal').value=record.daily_goal||'';$('#entries').replaceChildren(...record.gratitudes.map(entry));empty();fit() }
function entry(value,index){const row=document.createElement('article'),n=document.createElement('span'),copy=document.createElement('div'),p=document.createElement('p'),actions=document.createElement('div'),edit=document.createElement('button'),del=document.createElement('button');row.className='entry';n.className='number';n.textContent=index+1;copy.className='copy';p.textContent=value;copy.append(p);actions.className='actions';edit.textContent='✎';edit.ariaLabel='Edit gratitude';del.textContent='×';del.className='delete';del.ariaLabel='Delete gratitude';edit.onclick=()=>{const t=document.createElement('textarea'),buttons=document.createElement('div'),cancel=document.createElement('button'),save=document.createElement('button');t.className='editor';t.value=value;buttons.className='row';cancel.className='secondary';cancel.textContent='Cancel';save.className='primary';save.textContent='Save';cancel.onclick=()=>render();save.onclick=()=>{if(!t.value.trim())return t.focus();record.gratitudes[index]=t.value.trim();persist()};buttons.append(cancel,save);copy.replaceChildren(t,buttons);t.focus()};del.onclick=()=>{record.gratitudes.splice(index,1);persist()};actions.append(edit,del);row.append(n,copy,actions);return row}
async function persist(){record.daily_goal=$('#goal').value.trim();cache();render();if(!user||!client)return show('Saved on this device');show('Saving…');const {error}=await client.from('daily_journals').upsert({user_id:user.id,journal_date:day,daily_goal:record.daily_goal,gratitudes:record.gratitudes},{onConflict:'user_id,journal_date'});show(error?'Saved locally — retry when online':'Saved securely to your account')}
async function load(target=localDay()){day=target;record=JSON.parse(localStorage.getItem(cacheKey())||'{"daily_goal":"","gratitudes":[]}');if(user&&client){const {data}=await client.from('daily_journals').select('daily_goal,gratitudes').eq('user_id',user.id).eq('journal_date',day).maybeSingle();if(data)record=data}render()}
async function history(){const {data,error}=await client.from('daily_journals').select('journal_date,daily_goal,gratitudes').eq('user_id',user.id).lt('journal_date',localDay()).order('journal_date',{ascending:false});const list=$('#days');list.replaceChildren();if(error||!data?.length){list.textContent='No saved previous days yet.';return}data.forEach(x=>{const b=document.createElement('button');b.className='day';b.innerHTML=`<strong>${format(x.journal_date)}</strong><small>${x.gratitudes.length} gratitude${x.gratitudes.length===1?'':'s'}${x.daily_goal?' · Daily goal':''}</small>`;b.onclick=()=>{showToday();load(x.journal_date)};list.append(b)})}
function showToday(){$('#today').hidden=false;$('#history').hidden=true;$('#todaybtn').classList.add('active');$('#historybtn').classList.remove('active')}function showHistory(){$('#today').hidden=true;$('#history').hidden=false;$('#todaybtn').classList.remove('active');$('#historybtn').classList.add('active');history()}
async function session(s){user=s?.user;if(!user){auth.hidden=false;journal.hidden=true;return}auth.hidden=true;journal.hidden=false;$('#who').textContent=user.email;await load()}
if(!ready){$('#authmsg').textContent='Add your Supabase URL and publishable key to config.js first.'}else{client=createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);client.auth.getSession().then(({data})=>session(data.session));client.auth.onAuthStateChange((_e,s)=>session(s));$('#signin').onclick=async()=>{const {error}=await client.auth.signInWithPassword({email:$('#email').value,password:$('#password').value});$('#authmsg').textContent=error?.message||'Signed in.'};$('#signup').onclick=async()=>{const {error}=await client.auth.signUp({email:$('#email').value,password:$('#password').value,options:{emailRedirectTo:location.origin}});$('#authmsg').textContent=error?.message||'Check your email to confirm your account.'};$('#magic').onclick=async()=>{const {error}=await client.auth.signInWithOtp({email:$('#email').value,options:{emailRedirectTo:location.origin}});$('#authmsg').textContent=error?.message||'Check your email for your sign-in link.'};$('#out').onclick=()=>client.auth.signOut()}
$('#goal').oninput=()=>{fit();persist()};$('#add').onclick=()=>{$('#new').hidden=false;$('#add').hidden=true;$('#draft').focus()};$('#cancel').onclick=()=>{$('#new').hidden=true;$('#add').hidden=false};$('#saveentry').onclick=()=>{const x=$('#draft');if(!x.value.trim())return x.focus();record.gratitudes.push(x.value.trim());x.value='';$('#new').hidden=true;$('#add').hidden=false;persist()};$('#todaybtn').onclick=()=>{showToday();load()};$('#historybtn').onclick=showHistory;$('#dark').onclick=()=>{document.documentElement.style.colorScheme=document.documentElement.style.colorScheme==='dark'?'light':'dark';$('#dark').textContent=document.documentElement.style.colorScheme==='dark'?'Light mode':'Dark mode'};
